import React from "react";
import { Link, Post, Break, Image } from "../elements";

export default () => (
  <Post
    title="Modeling Tools"
    subtitle="Constraint-Based Modeling: Panel Designer & Façade Painter"
  >
    Under the supervision of <Link>Nate Holland</Link>
    <Break />
    <Image name="facade-painter">
      Rendered view of full-resolution geometry generated by the Facade Painter.
    </Image>
    <br />
    In design computation team at <Link>NBBJ</Link>, we worked on solutions to
    aid the design and modeling process of building facades, which are often
    complex and unwieldy to manipulate and iterate on in existing building
    information modeling pipelines. Our solution allowed users to model a module
    or a set of pattern modules responsively with constraints in Rhino3D and
    pattern them adaptively and parameterically using Grasshopper3D. After the
    initial design is set, further work exports the geometry and parameters to a
    higher-detail format for processing in Autodesk Revit.
    <Break />
    <Image name="facade-toolkit">Prototype user interface.</Image>
    <Break />
    In this work, the designer is able to quickly insert and remove constraints,
    and constraints are responsive and flexible to user editing. Our custom
    implementation allows users to model flexibly and quickly, and immediately
    see the impact of their changes at a building level in an interactive tool.
    <Break />
    <Image name="panel-designer">
      Workflow overview for single Panel Designer workspace.
    </Image>
    <br />
    In practice, this tool was able to save tens of hours on each project in the
    early design phase for teams iterating quickly on facade curtain wall design
    compared to modeling traditionally or within Revit directly. This work was
    presented and demonstrated in an <Link src="AU18">industry talk</Link> at
    Autodesk University 2018.
  </Post>
);
